---  
title: "HDR Attributes"
output:  
  html_document:  
    code_folding: hide
    toc: true
    toc_float:
      collapsed: false
    css: styles.css
---  

<br>

# What's new

  * Added CAS_04 HDR records since they are different from CASFRI specs (2019-05-21)
  * HDR attributes are ready to reviewed (2019-05-14)

<br>

# Overview

  * The CASFRI attribute names for CAS_04 are very different from the specifications.
  * The HDR attributes table for CAS_04 consists of three rows, one per inventory_standard_code.
  * It might be easiest to create this table manually since there is no need to loop over all records
  * The latest inventory_standard_cd attribute includes 4 categories: F, V, I, and L which was not present or used in CAS_04
    - what is L and should we include it?
    - was it present in past inventories and ignored?
<br>

# HDR Attributes (CAS_04)

```{r echo=FALSE, message=FALSE, warning=FALSE}  
z = read_csv("data/cas04_hdr.csv") %>% filter(header_id %in% c("BC_0004","BC_0005","BC_0006"))
dfSummary(z, graph.col=FALSE, valid.col=FALSE)
```

<br>

# CAS_05 Attributes

  * If the decision is to use the CAS_04 attributes rather than the attributes in the CASFRI specifications documents then the following sections can be deleted.

## identification_id {.tabset}

  * "mapInt(inventory_standard_cd, 'F,V,I,L', '4,5,6,0')"

## jurisdiction {.tabset}

  * copyText('BC')

## coordinate_sys {.tabset}

  * nothing()

## projection {.tabset}

  * nothing()

## datum {.tabset}

  * nothing()

## inventory_owner {.tabset}

  * copyText('PROV_GOV')

## land_owner {.tabset}

  * copyText('MOF')

## permission {.tabset}

  * nothing()

## tenure_type {.tabset}

  * nothing()

## inv_type {.tabset}

  * can we allow multiple types in CASFRI and with the copyText function?
  * the alternative would be splitting in 3 separate inventories as before
  * copyText('FIP','VRI','I')

## inv_version {.tabset}

  * nothing()

## inv_start_yr {.tabset}

  * nothing()

## inv_finish_yr {.tabset}

  * nothing()

## inv_acq_id {.tabset}

  * nothing()

## inv_acq_yr {.tabset}

  * nothing()

## inv_update_yr {.tabset}

  * nothing()
