---
title: "Inventories"
output:
  html_document:
    keep_md: no
    css: styles.css
---

Welcome to the CASFRI 5.0 inventories translation pages.

  * [Click here to access the underlying github pages](https://github.com/prvernier/cas)

## Documentation  

The docs menu includes reference documents specifying the CASFRI standard. Currently, one document is available:

  * CAS Specifications - converted from the original 2011 Cosco document to markdown format for easy updating.
  * CAS Attributes (issues) - discussion about issues related to selected attributes.
  * CAS Attributes (table) - table of all attributes along with values, comments, and status update for pilot inventories.

## Inventories  

The four menu items (AB06, AB16, BC08, NB01) include information on the procedure for translating the raw inventory data to the CASFRI standard. Under each menu are 6 items, one for each category of attribute (HDR, CAS, LYR, NFL, DST, ECO). By selecting on one of the items, you will see the current progress on understanding and converting each attribute to the standard. For many of the attributes, there is also some R code that was used to test the procedure while creating the CSV translation tables. Each attribute is summarized in raw form (RAWFRI tab) and translated form (CASFRI tab).

## CAS05 Schema  

```{r echo=FALSE, message=FALSE, warning=FALSE}  
schema = read_csv("../casfri/docs/specifications/attributes/cas_schema.csv") %>% mutate_all(~replace(., is.na(.), ""))
knitr::kable(schema)
```