fo = file("specs/cas_specifications.md", "w")
x1 = readLines("specs/1_intro.md")
x2 = readLines("specs/2_hdr_attributes.md")
x3 = readLines("specs/3_cas_attributes.md")
x4 = readLines("specs/4_lyr_attributes.md")
x5 = readLines("specs/5_nfl_attributes.md")
x6 = readLines("specs/6_dst_attributes.md")
x7 = readLines("specs/7_eco_attributes.md")
x8 = readLines("specs/8_bibliography.md")
x9 = readLines("specs/9_appendices.md")
cat(x1, file=fo, sep="\n")
cat("\n\n", x2, file=fo, sep="\n")
cat("\n\n", x3, file=fo, sep="\n")
cat("\n\n", x4, file=fo, sep="\n")
cat("\n\n", x5, file=fo, sep="\n")
cat("\n\n", x6, file=fo, sep="\n")
cat("\n\n", x7, file=fo, sep="\n")
cat("\n\n", x8, file=fo, sep="\n")
cat("\n\n", x9, file=fo, sep="\n")
close(fo)
