
CREATE SERVER myserver
  FOREIGN DATA WRAPPER ogr_fdw
  OPTIONS (
	datasource 'nb_0001',
	format 'ESRI Shapefile' );

CREATE FOREIGN TABLE forest (
  fid bigint,
  geom Geometry(Polygon,4269),
  stdlab bigint,
  datasrc varchar,
  datayr integer,
  sitei varchar,
  voli varchar,
  fst integer,
  l1trti varchar,
  l1orig varchar,
  l1estyr integer,
  l1trt varchar,
  l1trtyr integer,
  l1s1 varchar,
  l1ds1 varchar,
  l1pr1 integer,
  l1s2 varchar,
  l1ds2 varchar,
  l1pr2 integer,
  l1s3 varchar,
  l1ds3 varchar,
  l1pr3 integer,
  l1s4 varchar,
  l1ds4 varchar,
  l1pr4 integer,
  l1s5 varchar,
  l1ds5 varchar,
  l1pr5 integer,
  l1ds varchar,
  l1cci integer,
  l1cc integer,
  l1stock integer,
  l1vs integer,
  l1ht integer,
  l1acs integer,
  l1dc integer,
  l1sc integer,
  l1funa varchar,
  l2trti varchar,
  l2orig varchar,
  l2estyr integer,
  l2trt varchar,
  l2trtyr integer,
  l2s1 varchar,
  l2ds1 varchar,
  l2pr1 integer,
  l2s2 varchar,
  l2ds2 varchar,
  l2pr2 integer,
  l2s3 varchar,
  l2ds3 varchar,
  l2pr3 integer,
  l2s4 varchar,
  l2ds4 varchar,
  l2pr4 integer,
  l2s5 varchar,
  l2ds5 varchar,
  l2pr5 integer,
  l2ds varchar,
  l2cci integer,
  l2cc integer,
  l2stock integer,
  l2vs integer,
  l2ht integer,
  l2acs integer,
  l2dc integer,
  l2sc integer,
  l2funa varchar,
  harv_id varchar,
  plant_id varchar,
  thin_id varchar,
  lic_key varchar,
  interpid bigint,
  voln integer,
  shape_area real,
  shape_len real
) SERVER myserver
OPTIONS (layer 'Forest');

