library(rmarkdown)

fo = file("../docs/specifications/cas_specifications.md", "w")

x1 = readLines("../docs/specifications/attributes/01_introduction.md")
x2 = readLines("../docs/specifications/attributes/02_hdr_attributes.md")
x3 = readLines("../docs/specifications/attributes/03_cas_attributes.md")
x4 = readLines("../docs/specifications/attributes/04_lyr_attributes.md")
x5 = readLines("../docs/specifications/attributes/05_nfl_attributes.md")
x6 = readLines("../docs/specifications/attributes/06_dst_attributes.md")
x7 = readLines("../docs/specifications/attributes/07_eco_attributes.md")
x8 = readLines("../docs/specifications/attributes/08_geo_attributes.md")
x9 = readLines("../docs/specifications/attributes/09_bibliography.md")
x10 = readLines("../docs/specifications/attributes/10_appendices.md")

cat("\n\n", x1, file=fo, sep="\n")
cat("\n\n", x2, file=fo, sep="\n")
cat("\n\n", x3, file=fo, sep="\n")
cat("\n\n", x4, file=fo, sep="\n")
cat("\n\n", x5, file=fo, sep="\n")
cat("\n\n", x6, file=fo, sep="\n")
cat("\n\n", x7, file=fo, sep="\n")
cat("\n\n", x8, file=fo, sep="\n")
cat("\n\n", x9, file=fo, sep="\n")
cat("\n\n", x10, file=fo, sep="\n")
close(fo)

#f2 = file("cas_specs.Rmd", "w")
#x0 = readLines("specifications/00_yml.md")
#cat(x0, file=fo, sep="\n")
#render("cas_specs.Rmd", output_dir="docs")
#file.copy("docs/cas_specs.md", "../casfri/docs/specifications/cas_specifications.md")
