---  
title: "CAS Attributes"
date: "Updated: `r format(Sys.time(), '%d %B %Y')`"
output:  
  html_document:  
    code_folding: hide
    toc: true
    toc_float:
      collapsed: true
    css: styles.css
---  




# CAS Base Polygon Attributes

The CAS base polygon data provides polygon specific information and links the original inventory polygon ID to the CAS ID. Identification attributes include original stand ID, CAS Stand ID, Mapsheet ID, and Identification ID. Polygon attributes include polygon area and polygon perimeter. Inventory Reference Year, Photo Year, and Administrative Unit are additional identifiers.

## 2.1 CAS_ID

CAS_ID
Attribute Value
CAS stand identification - unique number for each polygon within CAS
Alpha Numeric


## 2.2 ORIG_STAND_ID

ORIG_STAND_ID
Attribute Value
Original stand identification - unique number for each polygon within the original inventory
1 - 10,000,000

## 2.3 STAND_STRUCTURE

Structure is the physical arrangement or vertical pattern of organization of the vegetation within a polygon. A stand can be identified as single layered, multilayered, complex, or horizontal. A single layered stand has stem heights that do not vary significantly and the vegetation has only one main canopy layer.

A multilayered stand can have several distinct layers and each layer is significant, has a distinct height difference, and is evenly distributed. Generally the layers are intermixed and when viewed vertically, one layer is above the other. Layers can be treed or non-treed. Up to 9 layers are allowed; most inventories recognize only one or two layers. The largest number of layers recognized is in the British Columbia VRI with 9 followed by Saskatchewan SFVI with 7 and Manitoba FLI with 5. Each layer is assigned an independent description with the tallest layer described in the upper portion of the label. The number of layers and a ranking of the layers can also be assigned. Some inventories (e.g. Saskatchewan UTM, Quebec TIE, Prince Edward Island, and Nova Scotia) can imply that a second layer exists; however, the second layer is not described or only a species type is indicated.

Complex layered stands exhibit a high variation in tree heights. There is no single definitive forested layer as nearly all height classes (and frequently ages) are represented in the stand. The height is chosen from a stand midpoint usually followed by a height range.

Horizontal structure represents vegetated or non-vegetated land with two or more homogeneous strata located within other distinctly different homogeneous strata within the same polygon but the included strata are too small to map separately based on minimum polygon size rules. This attribute is also used to identify multi- label polygons identified in biophysical inventories such as Wood Buffalo National Park and Prince Albert National Park. The detailed table for stand structure is presented in Appendix 3.

STAND STRUCTURE
Attribute Value
Single layered - vegetation within a polygon where the heights do not vary significantly.
S
Multilayered - two or more distinct layers of vegetation occur. Each layer is significant, clearly observable and evenly distributed. Each layer is assigned an independent description.
M
Complex - stands exhibit a high variation of heights with no single
C
Horizontal - two or more significant strata within the same polygon; at least one of the strata is too small to delineate as a separate H polygon.
NA

| STAND STRUCTURE| Attribute Value |  
| :--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | :-------------- |  
| Single layered - vegetation within a polygon where the heights do not vary significantly. | S|  
| Multilayered - two or more distinct layers of vegetation occur. Each layer is significant, clearly observable and evenly distributed. Each layer is assigned an independent description. | M|  
| Complex - stands exhibit a high variation of heights with no single | C|  
| Horizontal - two or more significant strata within the same polygon; at least one of the strata is too small to delineate as a separate H polygon. | NA |  


## 2.4  NUM_OF_LAYERS

Number of Layers is an attribute related to stand structure and identifies how many layers have been identified for a particular polygon.

NUMBER_OF_LAYERS
Attribute Value
Identifies the number of vegetation or non vegetation layers assigned to a particular polygon. A maximum of 9 layers can be identified.
1 - 9


## 2.5 IDENTIFICATION_ID


IDENTIFICATION_ID
Attribute Value
Unique number for a particular inventory section
1 - 1000

## 2.6 MAP_SHEET_ID


MAPSHEET_ID
Attribute Value
Map sheet identification according to original naming convention for an inventory
Alpha Numeric


## 2.7 GIS_AREA

Each polygon area and perimeter is recorded.
  * CAS_04 calls these GIS_AREA, GIS_PERIMETER, and INVENTORY_AREA
  * What is the difference between GIS_AREA and INVENTORY_AREA
  * What units and level of precision should area and perimeter be measured?

POLYGON_AREA and POLYGON_PERIMETER
Attribute Value
Polygon area (ha).
0.1 - 10,000
Polygon perimeter (ha).
0.1 - infinity


## 2.8 GIS_PERIMETER


## 2.9 INVENTORY_AREA


## 2.10  PHOTO_YEAR

Photo Year is the year in which the inventory was considered initiated and completed. An inventory can take several years to complete; therefore, Photo Year Minimum and Maximum dates are included to identify the interval for when the inventory was completed. In some cases inventory reference year and air photo year are the same. Several years of successive or periodic acquisition are possible; therefore, a minimum and a maximum year are recorded.

PHOTO_YEAR_MIN and PHOTO_YEAR_MAX
Attribute Value
Photo Year Minimum - earliest year of aerial photo acquisition
1960 - 2020
Photo Year Maximum - last year of aerial photo acquisition
1960 - 2020


