# Read CAS_04 exported csv files and save selected attributes
# PV 2019-01-22

library(tidyverse)
baseDir3 = "C:/Users/beacons/Documents/CASFRI/CAS_04/TranslatedCASFiles/Version.00.03/TranslatedFiles/"
baseDir4 = "C:/Users/beacons/Documents/CASFRI/CAS_04/TranslatedCASFiles/Version.00.04/TranslatedFiles/"

# ab_0006
ab6 = read_csv(paste0(baseDir3,"AB/Current/AB_AVI 2.1/AB_0006/GB_S21_TWP/GB_S21_TWP.lyr")) %>%
    select(CROWN_CLOSURE_UPPER,CROWN_CLOSURE_LOWER,HEIGHT_UPPER,HEIGHT_LOWER,SPECIES_1,SPECIES_PER_1,SPECIES_2,SPECIES_PER_2,SPECIES_3,SPECIES_PER_3,SPECIES_4,SPECIES_PER_4,SPECIES_5,SPECIES_PER_5,SPECIES_6,SPECIES_PER_6)
write_csv(ab6, "ab_0006/cas_04/lyr.csv")

# ab_0016
x=list.dirs(paste0(baseDir3,"AB/Current/AB_AVI 2.1/AB_0016"))[-1]
ab16 = read_csv(paste0(x[1],"/","T059R04M6.lyr")) %>%
        select(CROWN_CLOSURE_UPPER,CROWN_CLOSURE_LOWER,HEIGHT_UPPER,HEIGHT_LOWER,SPECIES_1,SPECIES_PER_1,SPECIES_2,SPECIES_PER_2,SPECIES_3,SPECIES_PER_3,SPECIES_4,SPECIES_PER_4,SPECIES_5,SPECIES_PER_5,SPECIES_6,SPECIES_PER_6)
for (i in x[-1]) {
    lyr = list.files(i, pattern="lyr")
    y = read_csv(paste0(i,"/",lyr)) %>%
        select(CROWN_CLOSURE_UPPER,CROWN_CLOSURE_LOWER,HEIGHT_UPPER,HEIGHT_LOWER,SPECIES_1,SPECIES_PER_1,SPECIES_2,SPECIES_PER_2,SPECIES_3,SPECIES_PER_3,SPECIES_4,SPECIES_PER_4,SPECIES_5,SPECIES_PER_5,SPECIES_6,SPECIES_PER_6)
    ab16 = rbind(ab16,y)
}
write_csv(ab16, "ab_0016/cas_04/lyr.csv")

# bc_0008
x=list.dirs(paste0(baseDir4,"BC"))[-1]
bc8 = read_csv(paste0(x[1],"/","BC_082B.lyr")) %>%
        select(CROWN_CLOSURE_UPPER,CROWN_CLOSURE_LOWER,HEIGHT_UPPER,HEIGHT_LOWER,SPECIES_1,SPECIES_PER_1,SPECIES_2,SPECIES_PER_2,SPECIES_3,SPECIES_PER_3,SPECIES_4,SPECIES_PER_4,SPECIES_5,SPECIES_PER_5,SPECIES_6,SPECIES_PER_6)
for (i in x[-1]) {
    lyr = list.files(i, pattern="lyr")
    y = read_csv(paste0(i,"/",lyr)) %>%
        select(CROWN_CLOSURE_UPPER,CROWN_CLOSURE_LOWER,HEIGHT_UPPER,HEIGHT_LOWER,SPECIES_1,SPECIES_PER_1,SPECIES_2,SPECIES_PER_2,SPECIES_3,SPECIES_PER_3,SPECIES_4,SPECIES_PER_4,SPECIES_5,SPECIES_PER_5,SPECIES_6,SPECIES_PER_6)
    bc8 = rbind(bc8,y)
}
write_csv(bc8, "bc_0008/cas_04/lyr.csv")

# bc_0008 (TFL 48)

# nb_0001
nb1 = read_csv(paste0(baseDir4,"NB/NB_0001/NB_0001.lyr")) %>%
    select(CROWN_CLOSURE_UPPER,CROWN_CLOSURE_LOWER,HEIGHT_UPPER,HEIGHT_LOWER,SPECIES_1,SPECIES_PER_1,SPECIES_2,SPECIES_PER_2,SPECIES_3,SPECIES_PER_3,SPECIES_4,SPECIES_PER_4,SPECIES_5,SPECIES_PER_5,SPECIES_6,SPECIES_PER_6)
write_csv(nb1, "nb_0001/cas_04/lyr.csv")


