---  
title: "HDR Attributes"
date: "Updated: `r format(Sys.time(), '%d %B %Y')`"
output_dir: "../docs"
output:  
  html_document:  
    code_folding: hide
    toc: true
    toc_float:
      collapsed: false
    css: "../docs/styles.css"
---  

<br>

# Overview

  * The HDR attribute names for CAS_04 are very different from the original specifications.
  * It probably easiest to create this table manually since there is no need to loop over all records:
    - CAS_04 table: data/cas04_hdr.csv
    - CAS_05 table: data/cas05_hdr.csv
  * Have the photoyear_start and photoyear_end dates changed?

# Attributes {.tabset}

## CAS_04

```{r echo=FALSE, message=FALSE, warning=FALSE}  
z = read_csv("../data/cas04_hdr.csv") %>% filter(header_id=="NB_0001")
dfSummary(z, graph.col=FALSE, valid.col=FALSE)
```

## CAS_05

```{r echo=FALSE, message=FALSE, warning=FALSE}  
z = read_csv("../data/cas05_hdr.csv") %>% filter(header_id=="NB01")
dfSummary(z, graph.col=FALSE, valid.col=FALSE)
```

## CAS_05 (new method)

```{r echo=TRUE, message=FALSE, warning=FALSE}  
z = read_csv("../data/inventory_list_cas05.csv") %>% 
    filter(INVENTORY_ID=="NB01") %>%
    select(INVENTORY_ID,JURISDICTION,OWNER_TYPE,OWNER_NAME,STANDARD_TYPE,STANDARD_VERSION,STANDARD_ID,STANDARD_REVISION,INVENTORY_MANUAL,SRC_DATA_FORMAT,ACQUISITION_DATE,DATA_TRANSFER,RECEIVED_FROM,CONTACT_INFO,DATA_AVAILABILITY,REDISTRIBUTION,PERMISSION,LICENSE_AGREEMENT,PHOTO_YEAR_SRC,PHOTO_YEAR_START,PHOTO_YEAR_END)
dfSummary(z, graph.col=FALSE, valid.col=FALSE)
```
